[package]
name = "advent-of-code-24"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5.0"
colored = "2.2.0"
image = "0.25.5"
indoc = "2.0.5"
inquire = "0.7.5"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"
